// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Disease is the predicate function for disease builders.
type Disease func(*sql.Selector)

// Drug is the predicate function for drug builders.
type Drug func(*sql.Selector)

// DrugType is the predicate function for drugtype builders.
type DrugType func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)
