// Code generated by entc, DO NOT EDIT.

package employee

const (
	// Label holds the string label denoting the employee type in the database.
	Label = "employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldUserid holds the string denoting the userid field in the database.
	FieldUserid = "userid"

	// EdgeDrug holds the string denoting the drug edge name in mutations.
	EdgeDrug = "drug"

	// Table holds the table name of the employee in the database.
	Table = "employees"
	// DrugTable is the table the holds the drug relation/edge.
	DrugTable = "drugs"
	// DrugInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugInverseTable = "drugs"
	// DrugColumn is the table column denoting the drug relation/edge.
	DrugColumn = "employee_drug"
)

// Columns holds all SQL columns for employee fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldUserid,
}
