// Code generated by entc, DO NOT EDIT.

package disease

const (
	// Label holds the string label denoting the disease type in the database.
	Label = "disease"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeDrug holds the string denoting the drug edge name in mutations.
	EdgeDrug = "drug"

	// Table holds the table name of the disease in the database.
	Table = "diseases"
	// DrugTable is the table the holds the drug relation/edge.
	DrugTable = "drugs"
	// DrugInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugInverseTable = "drugs"
	// DrugColumn is the table column denoting the drug relation/edge.
	DrugColumn = "disease_drug"
)

// Columns holds all SQL columns for disease fields.
var Columns = []string{
	FieldID,
	FieldName,
}
